- name: install Elastic stack on Ubuntu
  apt:
    name:
      - elasticsearch
      - kibana
      - logstash
      - filebeat
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install Elastic stack on CentOS
  dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
      - filebeat
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: install nagios in Ubuntu
  apt:
    name:
      - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install grafana and influxdb on Ubuntu
  apt:
    name:
      - grafana
      - influxdb
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install grafana and influxdb on CentOS
  dnf:
    name:
      - grafana
      - influxdb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install prometheus in Ubuntu
  command: apt install prometheus -y
  when: ansible_distribution == "Ubuntu"

- name: install prometheus in CentOS
  command: snap install prometheus --classic
  when: ansible_distribution == "CentOS"

- name: install apache and php for Ubuntu server
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install httpd and php for CentOS
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  service:
    name: httpd
    state: started
  when: ansible_distribution == "CentOS"

- name: install mariadb package (CentOS)
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: "Mariadb- Restarting/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true
